INSERT INTO TBL_NAMES VALUES ("hap");
INSERT INTO TBL_NAMES VALUES ("happend");
INSERT INTO TBL_NAMES VALUES ("hello");
INSERT INTO TBL_NAMES VALUES ("hiii");
INSERT INTO TBL_NAMES VALUES ("hero");
INSERT INTO TBL_NAMES VALUES ("banana");